# Generated by Django 3.2 on 2021-04-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0016_auto_20210427_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_buff',
            name='prod_size',
        ),
        migrations.RemoveField(
            model_name='inv_buff',
            name='prod_unit',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='prod_size',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='prod_unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prod_size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='prod_unit',
        ),
        migrations.RemoveField(
            model_name='order_buff',
            name='prod_size',
        ),
        migrations.RemoveField(
            model_name='order_buff',
            name='prod_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_unit',
        ),
    ]
