# Generated by Django 3.2 on 2021-04-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0017_auto_20210430_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inv_buff',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='inv_buff',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='inv_buff',
            name='taxes',
        ),
    ]
