# Generated by Django 3.2 on 2021-04-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storedb', '0018_auto_20210430_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_buff',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='order_buff',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order_buff',
            name='taxes',
        ),
    ]
